version: '3.8'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlserver_container
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: ./ProvaPub.Api/Dockerfile
    container_name: prova_api
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__ctx: "Server=sqlserver;Database=Teste;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 20s

volumes:
  sqlserver_data:
